### ISSUE TITLE
Exception: Model prediction is only supported on macOS version 10.13

### ISSUE THREAD

**Issue by engahmed1190** [prisma-ai/torch2coreml#2]
Is there any way to run those models on Linux
 
```
Traceback (most recent call last):
  File "stylize-image.py", line 28, in <module>
    main()
  File "stylize-image.py", line 21, in main
    stylized_image = net.predict({'inputImage': image})['outputImage']
  File "/usr/local/lib/python2.7/dist-packages/coremltools/models/model.py", line 244, in predict
    raise Exception('Model prediction is only supported on macOS version 10.13.')
Exception: Model prediction is only supported on macOS version 10.13.
```

**Comment by opedge** [comment]
Unfortunately to run models you need macOS 10.13 or iOS 11. This is the requirement of coremltools/CoreML.

**Comment by engahmed1190** [comment]
Thanks
