### ISSUE TITLE
Loading Model error : torch.utils.serialization.read_lua_file.T7ReaderException

### ISSUE THREAD

**Issue by engahmed1190** [prisma-ai/torch2coreml#3]
After training a model from the example and trying to convert the model to core ml 

this error appears

 ```
File "convert-fast-neural-style.py", line 53, in <module>
    main()
  File "convert-fast-neural-style.py", line 39, in main
    'blue_bias': 103.939
  File "/usr/local/lib/python2.7/dist-packages/torch2coreml/_torch_converter.py", line 171, in convert
    torch_model = load_lua(model)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 599, in load_lua
    return reader.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 586, in read
    return self.read_table()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 514, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 563, in read_table
    v = self.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 584, in read
    return self.read_object()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 514, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 537, in read_object
    return reader_registry[cls_name](self, version)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 242, in read_nn_class
    attributes = reader.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 586, in read
    return self.read_table()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 514, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 563, in read_table
    v = self.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 586, in read
    return self.read_table()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 514, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 563, in read_table
    v = self.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 584, in read
    return self.read_object()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 514, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 543, in read_object
    "constructor").format(cls_name))
torch.utils.serialization.read_lua_file.T7ReaderException: don't know how to deserialize Lua class nn.InstanceNormalization. If you want to ignore this error and load this object as a dict, specify unknown_classes=True in reader's constructor
```

**Comment by GregOriol** [comment]
Did you train the model with instance normalization? It doesn't seem to be supported (yet?)

Got a somehow similar error when trying to convert one of the model examples from the jcjohnson repository:
```
$ th prepare_model.lua -input fast-neural-style/models/instance_norm/feathers.t7 -output prepared_models/instance_norm-feathers.t7
/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.InstanceNormalization>
stack traceback:
	[C]: in function 'error'
	/home/ubuntu/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	/home/ubuntu/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ubuntu/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ubuntu/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/home/ubuntu/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/ubuntu/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ubuntu/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	prepare_model.lua:27: in function 'main'
	prepare_model.lua:44: in main chunk
	[C]: in function 'dofile'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

**Comment by engahmed1190** [comment]
Yes , I have used instance normalization in training model . this is the main issue now that instance normalization is not support

**Comment by opedge** [comment]
InstanceNormalization layer is not supported by torch.nn package, it is a custom implementation by Justin Johnson. CoreML supports this layer type. 

I just updated repo to support custom layers, so you can add you own parser for unimplemented layers. Also I updated an example of fast-neural-style (https://github.com/prisma-ai/torch2coreml/tree/master/example/fast-neural-style) to support InstanceNormalization layer. 

Now iOS example app uses styles with instance_norm layer (setup.sh script converts models from instance_norm subdirectory).

**Comment by engahmed1190** [comment]
thanks , I have tried the prepare model and it works fine , but  facing an issue in the convert code 
```
Traceback (most recent call last):
  File "convert-fast-neural-style.py", line 5, in <module>
    from torch.nn import InstanceNorm3d
ImportError: cannot import name InstanceNorm3d
```
as you mentioned instance norm is not supported in torch.nn , how I can add unimplemented layer to torch.nn library

**Comment by opedge** [comment]
@engahmed1190 InstanceNormalization is not natively supported in Torch7, but it is supported in PyTorch, which I'm using to parse original Torch7 models.

In fast-neural-style example I implemented InstanceNormalization layer for legacy Torch7 model using PyTorch InstanceNorm3d from here: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/instancenorm.py

May be your version of installed PyTorch is outdated? InstanceNorm3d class is natively supported in current PyTorch distribution.

**Comment by engahmed1190** [comment]
@opedge , thanks pytorch was outdated and I have resolve this 

I think there is something missing in unknown_layer_conveter_fn missing arguments
 
```
 Converting prepared_models/the_scream.t7
Traceback (most recent call last):
  File "convert-fast-neural-style.py", line 176, in <module>
    main()
  File "convert-fast-neural-style.py", line 162, in main
    unknown_layer_converter_fn=convert_instance_norm
TypeError: convert() got an unexpected keyword argument 'unknown_layer_converter_fn'
```

**Comment by opedge** [comment]
@engahmed1190 You need to update torch2coreml to 0.2.0 version: https://pypi.python.org/pypi/torch2coreml

**Comment by GregOriol** [comment]
On my side, the new code works well: I get the mlmodels with instance norm and the iOS app works.

**Comment by engahmed1190** [comment]
Great , welcome 

> torch2coreml 0.2.0

Solved Thanks
